[ 탁호진 ] Assigment3
wecode-bootcamp-korea/45-backend-westagram-2 pull request #29
Opened 2023-04-26 08:30 UTC by Takhojin

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 사용자 확인 후 포스트 게시

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- tokken 확인 후 api 접근 가능하게 구현

<br />

## :: 테스트 결과 이미지
1. post 성공
<img width="224" alt="스크린샷 2023-04-26 오후 5 25 51" src="https://user-images.githubusercontent.com/125236449/234517078-1da41cbd-3d4e-4a42-b69f-3f25f8e39fde.png">
2. tokken 인증 실패

<img width="260" alt="스크린샷 2023-04-26 오후 5 25 38" src="https://user-images.githubusercontent.com/125236449/234517173-0d9292de-d0e8-4944-9569-295d5623c6f8.png">

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-04-26 10:21 UTC, Kang-kyunghun requested changes

2023-04-26 10:21 UTC, Kang-kyunghun commented on takhojin/utils/checkToken.js
> +    next();
1. token의 존재 여부를 확인하는 로직을 추가해 주세요.
2. verify 후 payload에 있는 user 정보를 req에 담는 로직을 추가해 주세요.

```suggestion
  try {
    const token = req.headers.authorization;
    // token의 존재 여부를 확인하는 로직 추가
    jwt.verify(token, secreteKey);
    //verify 후 payload에 있는 user 정보를 req에 담는 로직 추가
    
    next();
```

2023-04-26 10:21 UTC, Kang-kyunghun commented on takhojin/utils/checkToken.js
> +    res.status(400).json({ message: err.message });
1. catch 문이 실행 되었다는 것은 이미 error가 발생 했기 때문에 새롭게 에러를 만들 필요가 없습니다.
2. 따라서 catch가 실행 되렀을 때 적절한 status code와 message을 반환해 주면 됩니다.
3. 해당 로직은 인증과 관련된 로직이기 때문에 status code는 400보다는 401이 더 적절할 것 같습니다.
```suggestion
    res.status(401).json({ message: "INVALID_ACCESS_TOKEN" });
```

2023-04-27 04:34 UTC, Jon9Beom commented
LGTM 👍 고생많으셨습니다 :)

2023-04-27 04:34 UTC, merged