[장인석] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/45-backend-westagram-2 pull request #5
Opened 2023-04-18 08:54 UTC by innichang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 유저가 가질 수 있는 고유 값 몇개를 UNIQUE 로 설정해서 db로 넣으면서 회원가입 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 성공적인 회원가입 구현

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지file:///home/inseok/Pictures/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/assignment2_inseok.jpg
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지file:///home/inseok/Pictures/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/assignment2_inseok_postman.jpg
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
file:///home/inseok/Pictures/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/assignment2_inseok_mysq.jpg

<br />

## :: 기타 질문 및 특이 사항
--

2023-04-18 09:44 UTC, kyeongraekim requested changes

2023-04-18 09:44 UTC, kyeongraekim commented on Inseok_45/db/schema.sql
> +/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
- 깃헙에 올라와서는 안되는 스키마 파일이 올라와 있네요! 해당 내역 깃 캐시에서 삭제후 재 푸시해주세요!

2023-04-18 09:46 UTC, kyeongraekim requested changes

2023-04-18 09:46 UTC, kyeongraekim commented on Inseok_45/app.js
> +app.post('/signup', async (req, res) => {
- 해당 내용이 users 라는 리소스에 해당되는 엔드포인트임을 드러낼 수 있게 'users/signup' 정도로 수정해주세요!
- 본 피드백은 RESTful 한 엔드포인트를 설계할 수 있게 설정한 것이라고 이해해주시면 되겠습니다!

2023-04-19 00:13 UTC, innichang commented on Inseok_45/db/schema.sql
> +/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
db폴더 자체를 빼면 되는건가요?

2023-04-19 04:58 UTC, innichang commented on Inseok_45/db/schema.sql
> +/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
된것같습니다!

2023-04-19 05:43 UTC, merged