[장인석] Assignment 3,4,5: Express API - CRUD(1)
wecode-bootcamp-korea/45-backend-westagram-2 pull request #9
Opened 2023-04-19 08:00 UTC by innichang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 게시글 등록
- 전체 게시글 조회
- 유저 게시글 조회

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- HTTP통신과 typeORM을 이용한 API로 sql 작업 수행

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![server_on](https://user-images.githubusercontent.com/126100135/233008393-b9f10e12-7229-4ec2-8939-012f090c416a.jpg)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
-게시글 등록
![posts_success](https://user-images.githubusercontent.com/126100135/233008279-7b1659f2-df9d-478a-8ddb-b146c455ea1a.jpg)

file:///home/inseok/Pictures/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/posts_db.jpg

-전체 게시글 조회하기
![post_view](https://user-images.githubusercontent.com/126100135/233008709-3b682188-f37f-4627-9f33-c91a7c1e51bf.jpg)

-유저의 게시글 조회하기
![user_post_view](https://user-images.githubusercontent.com/126100135/233008823-75525366-cf6a-4b73-8308-0c51ace7614c.jpg)

<br />

## :: 기타 질문 및 특이 사항
-

2023-04-19 08:10 UTC, Jon9Beom commented on Inseok_45/app.js
> +})
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리팩토링해주세요.
- 아래 예제에서처럼 callback 방식의 비동기처리 혹은 async/await를 활용한 비동기처리의 두가지 방식 중 하나로 통일되게 리팩토링 하되, 가급적 가장 최근의 문법이자 사용하기 쉽고 가독성이 뛰어난 async/await를 활용하여 수정해주세요.
    
    ```jsx
    // Bad
    app.get("/posts", async (req, res) => {
        await myDataSource.manager.query(
            `SELECT 
                u.id AS userId,
                u.profile_Image AS userProfileImage,
                p.id AS postingId,
                p.title AS postingTitle,
                p.content AS postingContent
            FROM users u
            INNER JOIN posts p ON
            u.id = p.user_id
            `,
            (err, rows) => {
                res.status(200).json({ data: rows });
            }
        );
    });
    
    // Good - callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // Good - async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```

2023-04-19 08:10 UTC, Jon9Beom commented on Inseok_45/app.js
> +app.get('/users/post/view/4', async (req, res) => {
```suggestion
app.get('/users/post/view', async (req, res) => {
```
end point 끝에 `/4`는 왜 들어간걸까요? 중복되면 다른 엔드포인트 이름으로 return값에 맞게 적절히 수정해주면 됩니다!

2023-04-19 08:10 UTC, Jon9Beom commented on Inseok_45/app.js
> +    console.log(userPost);
```suggestion
```
console.log()는 지워서 올라올 수 있도록 해주세요.

2023-04-19 08:20 UTC, innichang commented on Inseok_45/app.js
> +app.get('/users/post/view/4', async (req, res) => {
id 가 4인 user의 post 정보를 가져왔다 해서 '4'를 넣었습니다.

2023-04-20 05:09 UTC, Jon9Beom commented on Inseok_45/app.js
> +        WHERE users.id = ${userId}
오전에 말씀드렸던 것 처럼 특히 where clause에서는 place holder(`?`) 방식을 사용할 수 있도록 해주세요~!

2023-04-20 06:42 UTC, Kang-kyunghun requested changes

2023-04-20 06:42 UTC, Kang-kyunghun commented on Inseok_45/app.js
> +        WHERE posts.user_id = users.id && users.id = ?
&&을 이용한 and 연산은 mysql에서만 가능한 문법입니다. 따라서 일반적으로 쓰이는 AND로 수정해 주시면 좋을 것 같습니다.
```suggestion
        WHERE posts.user_id = users.id AND users.id = ?
```

2023-04-20 06:46 UTC, innichang commented on Inseok_45/app.js
> +        WHERE posts.user_id = users.id && users.id = ?
수정하였습니다!

2023-04-20 06:58 UTC, merged